name: Python Application Deploy

on:
  push:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-1 # Adjust to your region
          role-to-assume: arn:aws:iam::022499047781:role/RepositoryPublisherRole
          role-session-name: RepoPublishPackage
          role-duration-seconds: 900

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine boto3

      - name: Build and Publish to CodeArtifact
        run: |
          DOMAIN="annalect"
          DOMAIN_OWNER="022499047781"
          REPO_NAME="my-python-repo"

          # Get authorization token and repository endpoint
          export TWINE_USERNAME="aws" >> $GITHUB_ENV
          export TWINE_PASSWORD=$(aws codeartifact get-authorization-token --domain $DOMAIN --domain-owner $DOMAIN_OWNER --query authorizationToken --output text) >> $GITHUB_ENV
          export TWINE_REPOSITORY_URL=$(aws codeartifact get-repository-endpoint --domain $DOMAIN --domain-owner $DOMAIN_OWNER --repository $REPO_NAME --format pypi --query repositoryEndpoint --output text) >> $GITHUB_ENV

          # Build and publish package
          python setup.py sdist bdist_wheel
          twine upload dist/*
